<?php

// Generate random first name
function randomFirstName() {
    $first_names = array(
        'Allison',
        'Arthur',
        'Ana',
        'Alex',
        'Arlene',
        'Alberto',
        'Barry',
        'Bertha',
        'Bill',
        'Bonnie',
        'Bret',
        'Beryl',
        'Chantal',
        'Cristobal',
        'Claudette',
        'Charley',
        'Cindy',
        'Chris',
        'Dean',
        'Dolly',
        'Danny',
        'Danielle',
        'Dennis',
        'Debby',
        'Erin',
        'Edouard',
        'Erika',
        'Earl',
        'Emily',
        'Ernesto',
        'Felix',
        'Fay',
        'Fabian',
        'Frances',
        'Franklin',
        'Florence',
        'Gabielle',
        'Gustav',
        'Grace',
        'Gaston',
        'Gert',
        'Gordon',
        'Humberto',
        'Hanna',
        'Henri',
        'Hermine',
        'Harvey',
        'Helene',
        'Iris',
        'Isidore',
        'Isabel',
        'Ivan',
        'Irene',
        'Isaac',
        'Jerry',
        'Josephine',
        'Juan',
        'Jeanne',
        'Jose',
        'Joyce',
        'Karen',
        'Kyle',
        'Kate',
        'Karl',
        'Katrina',
        'Kirk',
        'Lorenzo',
        'Lili',
        'Larry',
        'Lisa',
        'Lee',
        'Leslie',
        'Michelle',
        'Marco',
        'Mindy',
        'Maria',
        'Michael',
        'Noel',
        'Nana',
        'Nicholas',
        'Nicole',
        'Nate',
        'Nadine',
        'Olga',
        'Omar',
        'Odette',
        'Otto',
        'Ophelia',
        'Oscar',
        'Pablo',
        'Paloma',
        'Peter',
        'Paula',
        'Philippe',
        'Patty',
        'Rebekah',
        'Rene',
        'Rose',
        'Richard',
        'Rita',
        'Rafael',
        'Sebastien',
        'Sally',
        'Sam',
        'Shary',
        'Stan',
        'Sandy',
        'Tanya',
        'Teddy',
        'Teresa',
        'Tomas',
        'Tammy',
        'Tony',
        'Van',
        'Vicky',
        'Victor',
        'Virginie',
        'Vince',
        'Valerie',
        'Wendy',
        'Wilfred',
        'Wanda',
        'Walter',
        'Wilma',
        'William',
        'Kumiko',
        'Aki',
        'Miharu',
        'Chiaki',
        'Michiyo',
        'Itoe',
        'Nanaho',
        'Reina',
        'Emi',
        'Yumi',
        'Ayumi',
        'Kaori',
        'Sayuri',
        'Rie',
        'Miyuki',
        'Hitomi',
        'Naoko',
        'Miwa',
        'Etsuko',
        'Akane',
        'Kazuko',
        'Miyako',
        'Youko',
        'Sachiko',
        'Mieko',
        'Toshie',
        'Junko',
        'Johnathon',
        'Anthony',
        'Erasmo',
        'Raleigh',
        'Nancie',
        'Tama',
        'Camellia',
        'Augustine',
        'Christeen',
        'Luz',
        'Diego',
        'Lyndia',
        'Thomas',
        'Georgianna',
        'Leigha',
        'Alejandro',
        'Marquis',
        'Joan',
        'Stephania',
        'Elroy',
        'Zonia',
        'Buffy',
        'Sharie',
        'Blythe',
        'Gaylene',
        'Elida',
        'Randy',
        'Margarete',
        'Margarett',
        'Dion',
        'Tomi',
        'Arden',
        'Clora',
        'Laine',
        'Becki',
        'Margherita',
        'Bong',
        'Jeanice',
        'Qiana',
        'Lawanda',
        'Rebecka',
        'Maribel',
        'Tami',
        'Yuri',
        'Michele',
        'Rubi',
        'Larisa',
        'Lloyd',
        'Tyisha',
        'Samatha'
    );
    return $first_names[rand(0, count($first_names) - 1)];
}

// Generate random last name
function randomLastName() {
    $last_names = array(
        'Abbott',
        'Acevedo',
        'Acosta',
        'Adams',
        'Adkins',
        'Aguilar',
        'Aguirre',
        'Albert',
        'Alexander',
        'Alford',
        'Allen',
        'Allison',
        'Alston',
        'Alvarado',
        'Alvarez',
        'Anderson',
        'Andrews',
        'Anthony',
        'Armstrong',
        'Arnold',
        'Ashley',
        'Atkins',
        'Atkinson',
        'Austin',
        'Avery',
        'Avila',
        'Ayala',
        'Ayers',
        'Bailey',
        'Baird',
        'Baker',
        'Baldwin',
        'Ball',
        'Ballard',
        'Banks',
        'Barber',
        'Barker',
        'Barlow',
        'Barnes',
        'Barnett',
        'Barr',
        'Barrera',
        'Barrett',
        'Barron',
        'Barry',
        'Bartlett',
        'Barton',
        'Bass',
        'Bates',
        'Battle',
        'Bauer',
        'Baxter',
        'Beach',
        'Bean',
        'Beard',
        'Beasley',
        'Beck',
        'Becker',
        'Bell',
        'Bender',
        'Benjamin',
        'Bennett',
        'Benson',
        'Bentley',
        'Benton',
        'Berg',
        'Berger',
        'Bernard',
        'Berry',
        'Best',
        'Bird',
        'Bishop',
        'Black',
        'Blackburn',
        'Blackwell',
        'Blair',
        'Blake',
        'Blanchard',
        'Blankenship',
        'Blevins',
        'Bolton',
        'Bond',
        'Bonner',
        'Booker',
        'Boone',
        'Booth',
        'Bowen',
        'Bowers',
        'Bowman',
        'Boyd',
        'Boyer',
        'Boyle',
        'Bradford',
        'Bradley',
        'Bradshaw',
        'Brady',
        'Branch',
        'Bray',
        'Brennan',
        'Brewer',
        'Bridges',
        'Briggs',
        'Bright',
        'Britt',
        'Brock',
        'Brooks',
        'Brown',
        'Browning',
        'Bruce',
        'Bryan',
        'Bryant',
        'Buchanan',
        'Buck',
        'Buckley',
        'Buckner',
        'Bullock',
        'Burch',
        'Burgess',
        'Burke',
        'Burks',
        'Burnett',
        'Burns',
        'Burris',
        'Burt',
        'Burton',
        'Bush',
        'Butler',
        'Byers',
        'Byrd',
        'Cabrera',
        'Cain',
        'Calderon',
        'Caldwell',
        'Calhoun',
        'Callahan',
        'Camacho',
        'Cameron',
        'Campbell',
        'Campos',
        'Cannon',
        'Cantrell',
        'Cantu',
        'Cardenas',
        'Carey',
        'Carlson',
        'Carney',
        'Carpenter',
        'Carr',
        'Carrillo',
        'Carroll',
        'Carson',
        'Carter',
        'Carver',
        'Case',
        'Casey',
        'Cash',
        'Castaneda',
        'Castillo',
        'Castro',
        'Cervantes',
        'Chambers',
        'Chan',
        'Chandler',
        'Chaney',
        'Chang',
        'Chapman',
        'Charles',
        'Chase',
        'Chavez',
        'Chen',
        'Cherry',
        'Christensen',
        'Christian',
        'Church',
        'Clark',
        'Clarke',
        'Clay',
        'Clayton',
        'Clements',
        'Clemons',
        'Cleveland',
        'Cline',
        'Cobb',
        'Cochran',
        'Coffey',
        'Cohen',
        'Cole',
        'Coleman',
        'Collier',
        'Collins',
        'Colon',
        'Combs',
        'Compton',
        'Conley',
        'Conner',
        'Conrad',
        'Contreras',
        'Conway',
        'Cook',
        'Cooke',
        'Cooley',
        'Cooper',
        'Copeland',
        'Cortez',
        'Cote',
        'Cotton',
        'Cox',
        'Craft',
        'Craig',
        'Crane',
        'Crawford',
        'Crosby',
        'Cross',
        'Cruz',
        'Cummings',
        'Cunningham',
        'Curry',
        'Curtis',
        'Dale',
        'Dalton',
        'Daniel',
        'Daniels',
        'Daugherty',
        'Davenport',
        'David',
        'Davidson',
        'Davis',
        'Dawson',
        'Day',
        'Dean',
        'Decker',
        'Dejesus',
        'Delacruz',
        'Delaney',
        'Deleon',
        'Delgado',
        'Dennis',
        'Diaz',
        'Dickerson',
        'Dickson',
        'Dillard',
        'Dillon',
        'Dixon',
        'Dodson',
        'Dominguez',
        'Donaldson',
        'Donovan',
        'Dorsey',
        'Dotson',
        'Douglas',
        'Downs',
        'Doyle',
        'Drake',
        'Dudley',
        'Duffy',
        'Duke',
        'Duncan',
        'Dunlap',
        'Dunn',
        'Duran',
        'Durham',
        'Dyer',
        'Eaton',
        'Edwards',
        'Elliott',
        'Ellis',
        'Ellison',
        'Emerson',
        'England',
        'English',
        'Erickson',
        'Espinoza',
        'Estes',
        'Estrada',
        'Evans',
        'Everett',
        'Ewing',
        'Farley',
        'Farmer',
        'Farrell',
        'Faulkner',
        'Ferguson',
        'Fernandez',
        'Ferrell',
        'Fields',
        'Figueroa',
        'Finch',
        'Finley',
        'Fischer',
        'Fisher',
        'Fitzgerald',
        'Fitzpatrick',
        'Fleming',
        'Fletcher',
        'Flores',
        'Flowers',
        'Floyd',
        'Flynn',
        'Foley',
        'Forbes',
        'Ford',
        'Foreman',
        'Foster',
        'Fowler',
        'Fox',
        'Francis',
        'Franco',
        'Frank',
        'Franklin',
        'Franks',
        'Frazier',
        'Frederick',
        'Freeman',
        'French',
        'Frost',
        'Fry',
        'Frye',
        'Fuentes',
        'Fuller',
        'Fulton',
        'Gaines',
        'Gallagher',
        'Gallegos',
        'Galloway',
        'Gamble',
        'Garcia',
        'Gardner',
        'Garner',
        'Garrett',
        'Garrison',
        'Garza',
        'Gates',
        'Gay',
        'Gentry',
        'George',
        'Gibbs',
        'Gibson',
        'Gilbert',
        'Giles',
        'Gill',
        'Gillespie',
        'Gilliam',
        'Gilmore',
        'Glass',
        'Glenn',
        'Glover',
        'Goff',
        'Golden',
        'Gomez',
        'Gonzales',
        'Gonzalez',
        'Good',
        'Goodman',
        'Goodwin',
        'Gordon',
        'Gould',
        'Graham',
        'Grant',
        'Graves',
        'Gray',
        'Green',
        'Greene',
        'Greer',
        'Gregory',
        'Griffin',
        'Griffith',
        'Grimes',
        'Gross',
        'Guerra',
        'Guerrero',
        'Guthrie',
        'Gutierrez',
        'Guy',
        'Guzman',
        'Hahn',
        'Hale',
        'Haley',
        'Hall',
        'Hamilton',
        'Hammond',
        'Hampton',
        'Hancock',
        'Haney',
        'Hansen',
        'Hanson',
        'Hardin',
        'Harding',
        'Hardy',
        'Harmon',
        'Harper',
        'Harrell',
        'Harrington',
        'Harris',
        'Harrison',
        'Hart',
        'Hartman',
        'Harvey',
        'Hatfield',
        'Hawkins',
        'Hayden',
        'Hayes',
        'Haynes',
        'Hays',
        'Head',
        'Heath',
        'Hebert',
        'Henderson',
        'Hendricks',
        'Hendrix',
        'Henry',
        'Hensley',
        'Henson',
        'Herman',
        'Hernandez',
        'Herrera',
        'Herring',
        'Hess',
        'Hester',
        'Hewitt',
        'Hickman',
        'Hicks',
        'Higgins',
        'Hill',
        'Hines',
        'Hinton',
        'Hobbs',
        'Hodge',
        'Hodges',
        'Hoffman',
        'Hogan',
        'Holcomb',
        'Holden',
        'Holder',
        'Holland',
        'Holloway',
        'Holman',
        'Holmes',
        'Holt',
        'Hood',
        'Hooper',
        'Hoover',
        'Hopkins',
        'Hopper',
        'Horn',
        'Horne',
        'Horton',
        'House',
        'Houston',
        'Howard',
        'Howe',
        'Howell',
        'Hubbard',
        'Huber',
        'Hudson',
        'Huff',
        'Huffman',
        'Hughes',
        'Hull',
        'Humphrey',
        'Hunt',
        'Hunter',
        'Hurley',
        'Hurst',
        'Hutchinson',
        'Hyde',
        'Ingram',
        'Irwin',
        'Jackson',
        'Jacobs',
        'Jacobson',
        'James',
        'Jarvis',
        'Jefferson',
        'Jenkins',
        'Jennings',
        'Jensen',
        'Jimenez',
        'Johns',
        'Johnson',
        'Johnston',
        'Jones',
        'Jordan',
        'Joseph',
        'Joyce',
        'Joyner',
        'Juarez',
        'Justice',
        'Kane',
        'Kaufman',
        'Keith',
        'Keller',
        'Kelley',
        'Kelly',
        'Kemp',
        'Kennedy',
        'Kent',
        'Kerr',
        'Key',
        'Kidd',
        'Kim',
        'King',
        'Kinney',
        'Kirby',
        'Kirk',
        'Kirkland',
        'Klein',
        'Kline',
        'Knapp',
        'Knight',
        'Knowles',
        'Knox',
        'Koch',
        'Kramer',
        'Lamb',
        'Lambert',
        'Lancaster',
        'Landry',
        'Lane',
        'Lang',
        'Langley',
        'Lara',
        'Larsen',
        'Larson',
        'Lawrence',
        'Lawson',
        'Le',
        'Leach',
        'Leblanc',
        'Lee',
        'Leon',
        'Leonard',
        'Lester',
        'Levine',
        'Levy',
        'Lewis',
        'Lindsay',
        'Lindsey',
        'Little',
        'Livingston',
        'Lloyd',
        'Logan',
        'Long',
        'Lopez',
        'Lott',
        'Love',
        'Lowe',
        'Lowery',
        'Lucas',
        'Luna',
        'Lynch',
        'Lynn',
        'Lyons',
        'Macdonald',
        'Macias',
        'Mack',
        'Madden',
        'Maddox',
        'Maldonado',
        'Malone',
        'Mann',
        'Manning',
        'Marks',
        'Marquez',
        'Marsh',
        'Marshall',
        'Martin',
        'Martinez',
        'Mason',
        'Massey',
        'Mathews',
        'Mathis',
        'Matthews',
        'Maxwell',
        'May',
        'Mayer',
        'Maynard',
        'Mayo',
        'Mays',
        'Mcbride',
        'Mccall',
        'Mccarthy',
        'Mccarty',
        'Mcclain',
        'Mcclure',
        'Mcconnell',
        'Mccormick',
        'Mccoy',
        'Mccray',
        'Mccullough',
        'Mcdaniel',
        'Mcdonald',
        'Mcdowell',
        'Mcfadden',
        'Mcfarland',
        'Mcgee',
        'Mcgowan',
        'Mcguire',
        'Mcintosh',
        'Mcintyre',
        'Mckay',
        'Mckee',
        'Mckenzie',
        'Mckinney',
        'Mcknight',
        'Mclaughlin',
        'Mclean',
        'Mcleod',
        'Mcmahon',
        'Mcmillan',
        'Mcneil',
        'Mcpherson',
        'Meadows',
        'Medina',
        'Mejia',
        'Melendez',
        'Melton',
        'Mendez',
        'Mendoza',
        'Mercado',
        'Mercer',
        'Merrill',
        'Merritt',
        'Meyer',
        'Meyers',
        'Michael',
        'Middleton',
        'Miles',
        'Miller',
        'Mills',
        'Miranda',
        'Mitchell',
        'Molina',
        'Monroe',
        'Montgomery',
        'Montoya',
        'Moody',
        'Moon',
        'Mooney',
        'Moore',
        'Morales',
        'Moran',
        'Moreno',
        'Morgan',
        'Morin',
        'Morris',
        'Morrison',
        'Morrow',
        'Morse',
        'Morton',
        'Moses',
        'Mosley',
        'Moss',
        'Mueller',
        'Mullen',
        'Mullins',
        'Munoz',
        'Murphy',
        'Murray',
        'Myers',
        'Nash',
        'Navarro',
        'Neal',
        'Nelson',
        'Newman',
        'Newton',
        'Nguyen',
        'Nichols',
        'Nicholson',
        'Nielsen',
        'Nieves',
        'Nixon',
        'Noble',
        'Noel',
        'Nolan',
        'Norman',
        'Norris',
        'Norton',
        'Nunez',
        'Obrien',
        'Ochoa',
        'Oconnor',
        'Odom',
        'Odonnell',
        'Oliver',
        'Olsen',
        'Olson',
        'Oneal',
        'Oneil',
        'Oneill',
        'Orr',
        'Ortega',
        'Ortiz',
        'Osborn',
        'Osborne',
        'Owen',
        'Owens',
        'Pace',
        'Pacheco',
        'Padilla',
        'Page',
        'Palmer',
        'Park',
        'Parker',
        'Parks',
        'Parrish',
        'Parsons',
        'Pate',
        'Patel',
        'Patrick',
        'Patterson',
        'Patton',
        'Paul',
        'Payne',
        'Pearson',
        'Peck',
        'Pena',
        'Pennington',
        'Perez',
        'Perkins',
        'Perry',
        'Peters',
        'Petersen',
        'Peterson',
        'Petty',
        'Phelps',
        'Phillips',
        'Pickett',
        'Pierce',
        'Pittman',
        'Pitts',
        'Pollard',
        'Poole',
        'Pope',
        'Porter',
        'Potter',
        'Potts',
        'Powell',
        'Powers',
        'Pratt',
        'Preston',
        'Price',
        'Prince',
        'Pruitt',
        'Puckett',
        'Pugh',
        'Quinn',
        'Ramirez',
        'Ramos',
        'Ramsey',
        'Randall',
        'Randolph',
        'Rasmussen',
        'Ratliff',
        'Ray',
        'Raymond',
        'Reed',
        'Reese',
        'Reeves',
        'Reid',
        'Reilly',
        'Reyes',
        'Reynolds',
        'Rhodes',
        'Rice',
        'Rich',
        'Richard',
        'Richards',
        'Richardson',
        'Richmond',
        'Riddle',
        'Riggs',
        'Riley',
        'Rios',
        'Rivas',
        'Rivera',
        'Rivers',
        'Roach',
        'Robbins',
        'Roberson',
        'Roberts',
        'Robertson',
        'Robinson',
        'Robles',
        'Rocha',
        'Rodgers',
        'Rodriguez',
        'Rodriquez',
        'Rogers',
        'Rojas',
        'Rollins',
        'Roman',
        'Romero',
        'Rosa',
        'Rosales',
        'Rosario',
        'Rose',
        'Ross',
        'Roth',
        'Rowe',
        'Rowland',
        'Roy',
        'Ruiz',
        'Rush',
        'Russell',
        'Russo',
        'Rutledge',
        'Ryan',
        'Salas',
        'Salazar',
        'Salinas',
        'Sampson',
        'Sanchez',
        'Sanders',
        'Sandoval',
        'Sanford',
        'Santana',
        'Santiago',
        'Santos',
        'Sargent',
        'Saunders',
        'Savage',
        'Sawyer',
        'Schmidt',
        'Schneider',
        'Schroeder',
        'Schultz',
        'Schwartz',
        'Scott',
        'Sears',
        'Sellers',
        'Serrano',
        'Sexton',
        'Shaffer',
        'Shannon',
        'Sharp',
        'Sharpe',
        'Shaw',
        'Shelton',
        'Shepard',
        'Shepherd',
        'Sheppard',
        'Sherman',
        'Shields',
        'Short',
        'Silva',
        'Simmons',
        'Simon',
        'Simpson',
        'Sims',
        'Singleton',
        'Skinner',
        'Slater',
        'Sloan',
        'Small',
        'Smith',
        'Snider',
        'Snow',
        'Snyder',
        'Solis',
        'Solomon',
        'Sosa',
        'Soto',
        'Sparks',
        'Spears',
        'Spence',
        'Spencer',
        'Stafford',
        'Stanley',
        'Stanton',
        'Stark',
        'Steele',
        'Stein',
        'Stephens',
        'Stephenson',
        'Stevens',
        'Stevenson',
        'Stewart',
        'Stokes',
        'Stone',
        'Stout',
        'Strickland',
        'Strong',
        'Stuart',
        'Suarez',
        'Sullivan',
        'Summers',
        'Sutton',
        'Swanson',
        'Sweeney',
        'Sweet',
        'Sykes',
        'Talley',
        'Tanner',
        'Tate',
        'Taylor',
        'Terrell',
        'Terry',
        'Thomas',
        'Thompson',
        'Thornton',
        'Tillman',
        'Todd',
        'Torres',
        'Townsend',
        'Tran',
        'Travis',
        'Trevino',
        'Trujillo',
        'Tucker',
        'Turner',
        'Tyler',
        'Tyson',
        'Underwood',
        'Valdez',
        'Valencia',
        'Valentine',
        'Valenzuela',
        'Vance',
        'Vang',
        'Vargas',
        'Vasquez',
        'Vaughan',
        'Vaughn',
        'Vazquez',
        'Vega',
        'Velasquez',
        'Velazquez',
        'Velez',
        'Villarreal',
        'Vincent',
        'Vinson',
        'Wade',
        'Wagner',
        'Walker',
        'Wall',
        'Wallace',
        'Waller',
        'Walls',
        'Walsh',
        'Walter',
        'Walters',
        'Walton',
        'Ward',
        'Ware',
        'Warner',
        'Warren',
        'Washington',
        'Waters',
        'Watkins',
        'Watson',
        'Watts',
        'Weaver',
        'Webb',
        'Weber',
        'Webster',
        'Weeks',
        'Weiss',
        'Welch',
        'Wells',
        'West',
        'Wheeler',
        'Whitaker',
        'White',
        'Whitehead',
        'Whitfield',
        'Whitley',
        'Whitney',
        'Wiggins',
        'Wilcox',
        'Wilder',
        'Wiley',
        'Wilkerson',
        'Wilkins',
        'Wilkinson',
        'William',
        'Williams',
        'Williamson',
        'Willis',
        'Wilson',
        'Winters',
        'Wise',
        'Witt',
        'Wolf',
        'Wolfe',
        'Wong',
        'Wood',
        'Woodard',
        'Woods',
        'Woodward',
        'Wooten',
        'Workman',
        'Wright',
        'Wyatt',
        'Wynn',
        'Yang',
        'Yates',
        'York',
        'Young',
        'Zamora',
        'Zimmerman',
        'Mischke',
        'Serna',
        'Pingree',
        'Mcnaught',
        'Pepper',
        'Schildgen',
        'Mongold',
        'Wrona',
        'Geddes',
        'Lanz',
        'Fetzer',
        'Schroeder',
        'Block',
        'Mayoral',
        'Fleishman',
        'Roberie',
        'Latson',
        'Lupo',
        'Motsinger',
        'Drews',
        'Coby',
        'Redner',
        'Culton',
        'Howe',
        'Stoval',
        'Michaud',
        'Mote',
        'Menjivar',
        'Wiers',
        'Paris',
        'Grisby',
        'Noren',
        'Damron',
        'Kazmierczak',
        'Haslett',
        'Guillemette',
        'Buresh',
        'Center',
        'Kucera',
        'Catt',
        'Badon',
        'Grumbles',
        'Antes',
        'Byron',
        'Volkman',
        'Klemp',
        'Pekar',
        'Pecora',
        'Schewe',
        'Ramage'
    );
    return $last_names[rand(0, count($last_names) - 1)];
}

// Generate random sex
function randomSex() {
    $sexes = array(
        'Male',
        'Female'
    );
    return $sexes[rand(0, count($sexes) - 1)];
}

// Generate random country and flag
$countries = array(
    'AF' => 'Afghanistan',
    'AX' => '&Aring;land Islands',
    'AL' => 'Albania',
    'DZ' => 'Algeria',
    'AS' => 'American Samoa',
    'AD' => 'Andorra',
    'AO' => 'Angola',
    'AI' => 'Anguilla',
    'AG' => 'Antigua and Barbuda',
    'AR' => 'Argentina',
    'AM' => 'Armenia',
    'AW' => 'Aruba',
    'AU' => 'Australia',
    'AT' => 'Austria',
    'AZ' => 'Azerbaijan',
    'BS' => 'Bahamas (the)',
    'BH' => 'Bahrain',
    'BD' => 'Bangladesh',
    'BB' => 'Barbados',
    'BY' => 'Belarus',
    'BE' => 'Belgium',
    'BZ' => 'Belize',
    'BJ' => 'Benin',
    'BM' => 'Bermuda',
    'BT' => 'Bhutan',
    'BO' => 'Bolivia (Plurinational State of)',
    'BA' => 'Bosnia and Herzegovina',
    'BW' => 'Botswana',
    'BV' => 'Bouvet Island',
    'BR' => 'Brazil',
    'IO' => 'British Indian Ocean Territory (the)',
    'BN' => 'Brunei Darussalam',
    'BG' => 'Bulgaria',
    'BF' => 'Burkina Faso',
    'BI' => 'Burundi',
    'KH' => 'Cambodia',
    'CV' => 'Cabo Verde',
    'CM' => 'Cameroon',
    'CA' => 'Canada',
    'CT' => 'Catalonia',
    'KY' => 'Cayman Islands (the)',
    'CF' => 'Central African Republic (the)',
    'TD' => 'Chad',
    'CL' => 'Chile',
    'CN' => 'China',
    'CX' => 'Christmas Island',
    'CC' => 'Cocos (Keeling) Islands (the)',
    'CO' => 'Colombia',
    'KM' => 'Comoros',
    'CD' => 'Congo (the Democratic Republic of the)',
    'CG' => 'Congo (the)',
    'CK' => 'Cook Islands (the)',
    'CR' => 'Costa Rica',
    'CI' => 'C&ocirc;te d\'Ivoire',
    'HR' => 'Croatia',
    'CU' => 'Cuba',
    'CY' => 'Cyprus',
    'CZ' => 'Czech Republic (the)',
    'DK' => 'Denmark',
    'DJ' => 'Djibouti',
    'DM' => 'Dominica',
    'DO' => 'Dominican Republic (the)',
    'EC' => 'Ecuador',
    'EG' => 'Egypt',
    'SV' => 'El Salvador',
    'EN' => 'England',
    'GQ' => 'Equatorial Guinea',
    'ER' => 'Eritrea',
    'EE' => 'Estonia',
    'ET' => 'Ethiopia',
    'EU' => 'European Union',
    'FK' => 'Falkland Islands (the) [Malvinas]',
    'FO' => 'Faroe Islands (the)',
    'FJ' => 'Fiji',
    'FI' => 'Finland',
    'FR' => 'France',
    'GF' => 'French Guiana',
    'PF' => 'French Polynesia',
    'TF' => 'French Southern Territories (the)',
    'GA' => 'Gabon',
    'GM' => 'Gambia (the)',
    'GE' => 'Georgia',
    'DE' => 'Germany',
    'GH' => 'Ghana',
    'GI' => 'Gibraltar',
    'GR' => 'Greece',
    'GL' => 'Greenland',
    'GD' => 'Grenada',
    'GP' => 'Guadeloupe',
    'GU' => 'Guam',
    'GT' => 'Guatemala',
    'GN' => 'Guinea',
    'GW' => 'Guinea-Bissau',
    'GY' => 'Guyana',
    'HT' => 'Haiti',
    'HM' => 'Heard Island and McDonald Islands',
    'VA' => 'Holy See (the)',
    'HN' => 'Honduras',
    'HK' => 'Hong Kong',
    'HU' => 'Hungary',
    'IS' => 'Iceland',
    'IN' => 'India',
    'ID' => 'Indonesia',
    'IR' => 'Iran (Islamic Republic of)',
    'IQ' => 'Iraq',
    'IE' => 'Ireland',
    'IL' => 'Israel',
    'IT' => 'Italy',
    'JM' => 'Jamaica',
    'JP' => 'Japan',
    'JO' => 'Jordan',
    'KZ' => 'Kazakhstan',
    'KE' => 'Kenya',
    'KI' => 'Kiribati',
    'KP' => 'Korea (the Democratic People\'s Republic of)',
    'KR' => 'Korea (the Republic of)',
    'KW' => 'Kuwait',
    'KG' => 'Kyrgyzstan',
    'LA' => 'Lao People\'s Democratic Republic (the)',
    'LV' => 'Latvia',
    'LB' => 'Lebanon',
    'LS' => 'Lesotho',
    'LR' => 'Liberia',
    'LY' => 'Libya',
    'LI' => 'Liechtenstein',
    'LT' => 'Lithuania',
    'LU' => 'Luxembourg',
    'MO' => 'Macao',
    'MK' => 'Macedonia (the former Yugoslav Republic of)',
    'MG' => 'Madagascar',
    'MW' => 'Malawi',
    'MY' => 'Malaysia',
    'MV' => 'Maldives',
    'ML' => 'Mali',
    'MT' => 'Malta',
    'MH' => 'Marshall Islands (the)',
    'MQ' => 'Martinique',
    'MR' => 'Mauritania',
    'MU' => 'Mauritius',
    'YT' => 'Mayotte',
    'MX' => 'Mexico',
    'FM' => 'Micronesia (Federated States of)',
    'MD' => 'Moldova (the Republic of)',
    'MC' => 'Monaco',
    'MN' => 'Mongolia',
    'ME' => 'Montenegro',
    'MS' => 'Montserrat',
    'MA' => 'Morocco',
    'MZ' => 'Mozambique',
    'MM' => 'Myanmar',
    'NA' => 'Namibia',
    'NR' => 'Nauru',
    'NP' => 'Nepal',
    'NL' => 'Netherlands (the)',
    'AN' => 'Netherlands Antilles',
    'NC' => 'New Caledonia',
    'NZ' => 'New Zealand',
    'NI' => 'Nicaragua',
    'NE' => 'Niger (the)',
    'NG' => 'Nigeria',
    'NU' => 'Niue',
    'NF' => 'Norfolk Island',
    'MP' => 'Northern Mariana Islands (the)',
    'NO' => 'Norway',
    'OM' => 'Oman',
    'PK' => 'Pakistan',
    'PW' => 'Palau',
    'PS' => 'Palestine, State of',
    'PA' => 'Panama',
    'PG' => 'Papua New Guinea',
    'PY' => 'Paraguay',
    'PE' => 'Peru',
    'PH' => 'Philippines (the)',
    'PN' => 'Pitcairn',
    'PL' => 'Poland',
    'PT' => 'Portugal',
    'PR' => 'Puerto Rico',
    'QA' => 'Qatar',
    'RE' => 'R&eacute;union',
    'RO' => 'Romania',
    'RU' => 'Russian Federation (the)',
    'RW' => 'Rwanda',
    'SH' => 'Saint Helena, Ascension and Tristan da Cunha',
    'KN' => 'Saint Kitts and Nevis',
    'LC' => 'Saint Lucia',
    'PM' => 'Saint Pierre and Miquelon',
    'VC' => 'Saint Vincent and the Grenadines',
    'WS' => 'Samoa',
    'SM' => 'San Marino',
    'ST' => 'Sao Tome and Principe',
    'SA' => 'Saudi Arabia',
    'AB' => 'Scotland',
    'SN' => 'Senegal',
    'RS' => 'Serbia',
    'CS' => 'Serbia and Montenegro',
    'SC' => 'Seychelles',
    'SL' => 'Sierra Leone',
    'SG' => 'Singapore',
    'SK' => 'Slovakia',
    'SI' => 'Slovenia',
    'SB' => 'Solomon Islands',
    'SO' => 'Somalia',
    'ZA' => 'South Africa',
    'GS' => 'South Georgia and the South Sandwich Islands',
    'ES' => 'Spain',
    'LK' => 'Sri Lanka',
    'SD' => 'Sudan (the)',
    'SR' => 'Suriname',
    'SJ' => 'Svalbard and Jan Mayen',
    'SZ' => 'Swaziland',
    'SE' => 'Sweden',
    'CH' => 'Switzerland',
    'SY' => 'Syrian Arab Republic',
    'TW' => 'Taiwan (Province of China)',
    'TJ' => 'Tajikistan',
    'TZ' => 'Tanzania, United Republic of',
    'TH' => 'Thailand',
    'TL' => 'Timor-Leste',
    'TG' => 'Togo',
    'TK' => 'Tokelau',
    'TO' => 'Tonga',
    'TT' => 'Trinidad and Tobago',
    'TN' => 'Tunisia',
    'TR' => 'Turkey',
    'TM' => 'Turkmenistan',
    'TC' => 'Turks and Caicos Islands (the)',
    'TV' => 'Tuvalu',
    'UG' => 'Uganda',
    'UA' => 'Ukraine',
    'AE' => 'United Arab Emirates (the)',
    'GB' => 'United Kingdom of Great Britain and Northern Ireland (the)',
    'UM' => 'United States Minor Outlying Islands (the)',
    'US' => 'United States of America (the)',
    'UY' => 'Uruguay',
    'UZ' => 'Uzbekistan',
    'VU' => 'Vanuatu',
    'VE' => 'Venezuela (Bolivarian Republic of)',
    'VN' => 'Viet Nam',
    'VG' => 'Virgin Islands (British)',
    'VI' => 'Virgin Islands (U.S.)',
    'WA' => 'Wales',
    'WF' => 'Wallis and Futuna',
    'EH' => 'Western Sahara',
    'YE' => 'Yemen',
    'ZM' => 'Zambia',
    'ZW' => 'Zimbabwe'
);
function randomCountry($list) {
    $key = array_rand($list);
    $value = $list[$key];
    return $value;
}
function randomCountryFlag($list) {
    $key = array_rand($list);
    return strtolower($key);
}

// Generate random phone number
function phoneNumber() {
    $numbers = array(
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '0'
    );
    return $numbers[rand(0, count($numbers) - 1)];
}

// Generate random birthday
function birtday($years) {
    $date = strtotime(date("Y").'-'.phoneNumber().'-'.phoneNumber().' -'.$years.' year');
    return date('Y-m-d', $date);
}



$first_name = randomFirstName();
$last_name = randomLastName();
$sex = randomSex();
$age = (rand(18,75));
$birthdayDate = birtday($age);
$country = randomCountry($countries);
$flag = randomCountryFlag($countries);

?>

<img src="avatar.png" alt="" width="128px">
<span style="display: inline-block; vertical-align: bottom; margin-left: 2rem;">
    <h4 ><?php echo $first_name . " " . $last_name; ?></h4>
    <p><?php echo $age; ?> years old · born <?php echo $birthdayDate; ?><br>
    From <?php print_r($country); ?></p>
</span>

<br><br><br>
<ul class="list-group">
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Display Name<span class="text-success"><?php echo $first_name . " " . $last_name; ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        First Name<span class="text-success"><?php echo $first_name; ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Last Name<span class="text-success"><?php echo $last_name; ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Age<span class="text-success"><?php echo $age; ?> years old</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Birthday<span class="text-success"><?php echo $birthdayDate; ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Sex<span class="text-success"><?php echo $sex; ?></span>
    </li>

    <hr>

    <li class="list-group-item d-flex justify-content-between align-items-center">
        Country<span class="text-success"><?php print_r($country); ?> <img src="flags/<?php print_r($flag); ?>.gif" alt="Flag of <?php print_r($country); ?>" title="Flag of <?php print_r($country); ?>"></span>
    </li>

    <hr>

    <li class="list-group-item d-flex justify-content-between align-items-center">
        Phone Number<span class="text-success"><?php echo phoneNumber() . phoneNumber() . phoneNumber(); ?>-<?php echo phoneNumber() . phoneNumber() . phoneNumber(); ?>-<?php echo phoneNumber() . phoneNumber() . phoneNumber() . phoneNumber(); ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Country Code<span class="text-success">1</span>
    </li>

    <hr>


</ul>
